<?php
/**
 * BSD 3-Clause License
 *
 * Copyright (c) 2019, TASoft Applications
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

use Skyline\Navigation\NavigationService;


?>
<div class="container-fluid mt-3 main-container">
    <header class="m-0 mx-sm-3 mt-sm-3 sticky-fixed">
        <?php
        /** @var NavigationService $nv */
        $nv = $this->mainNavigation;

        $topNav = $nv->getNavigationBar("top-navigation");
        $nv->renderNavigation($topNav);
        ?>
        <div class="container pt-3 pb-5 d-flex justify-content-end">
            <div class="well">
                <h2 class="mb-0"><span class="tasoft-primary-text">TA</span>Soft <span class="tasoft-primary-text">App</span>lications</h2>
                <p>
                    Ihre Lösungen rund um Programmierung und Entwicklung
                </p>
            </div>
        </div>
    </header>

    <div class="container p-0 p-sm-1">
        <main class="p-3 sticky-flexible">
            <?php
            $this->renderSubTemplate("Content");
            ?>
        </main>
    </div>

    <footer class="sticky-bottom m-0 mx-sm-3 mb-sm-3">
        <div class="container py-1">
            © 2019 TASoft
            <p class="text-muted font-italic" style="font-size: 80%">
                Powered by Skyline CMS. Alle Rechte vorbehalten.
            </p>
        </div>
    </footer>
</div>
