<?php
/**
 * BSD 3-Clause License
 *
 * Copyright (c) 2019, TASoft Applications
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

use Skyline\Render\Context\DefaultRenderContext;
use TASoft\Service\ServiceManager;

/**
 *
 * @var DefaultRenderContext $this
 */
?>
<style type="text/css">
	.btn.action {
		padding-top: 0.5em;
		padding-bottom: 0.5em;
		border-top-left-radius: 5em;
		border-top-right-radius: 5em;
		border-bottom-left-radius: 5em;
		border-bottom-right-radius: 5em;
		padding-left: 0.5em;
		padding-right: 0.5em;
		width: 3.5em;
		height: 3.5em;
		text-align: center;
		vertical-align: center;
	}

	.md-form {
		margin-bottom: 2rem;
	}
</style>
<h1><?=$this->translate("Configuration")?></h1>
<div class="alert alert-primary">
	<?=$this->translate('Your Skyline CMS Administration panel is not yet ready to use. Please go through the following steps to configure the application.')?>
</div>

<hr>

<div class="row">
	<div class="col-md-6 mt-3">
		<div class="card">
			<h4 class="card-header"><?=$this->translate("Security")?></h4>
			<div class="card-body">
				<p>
					<?= $this->translate('The security system is responsable to grant or deny access to your administration pages or also your website (if needed).<br>
					There are some settings you need to decide, how Skyline CMS should handle cases.') ?>
				</p>
				<span class="badge badge-danger badge-pill"><?= $this->translate('Not yet configured') ?></span>
			</div>
			<div class="card-footer d-flex justify-content-between">
				<button class="btn-sm btn btn-primary" onclick="location.href='<?=$this->buildURL('Admin', '/config-security')?>'"><?= $this->translate('Setup') ?></button>
			</div>
		</div>
	</div>

	<div class="col-md-6 mt-3">
		<div class="card">
			<h4 class="card-header"><?=$this->translate("User System")?></h4>
			<div class="card-body">
				<p>
					<?= $this->translate('With the user system you can switch between two different login systems.<br>
					There is a simple login system (without database) and a complex.') ?>
				</p>
				<span class="badge badge-danger badge-pill"><?= $this->translate('Not yet configured') ?></span>
				<span class="badge badge-warning badge-pill"><?= $this->translate('Works with current setup') ?></span>
			</div>
			<div class="card-footer d-flex justify-content-between">
				<button class="btn-sm btn btn-primary" onclick="location.href='<?=$this->buildURL('Admin', '/config-user-system')?>'"><?= $this->translate('Setup') ?></button>
			</div>
		</div>
	</div>

	<div class="col-md-6 mt-3">
		<div class="card">
			<h4 class="card-header"><?=$this->translate("Database")?></h4>
			<div class="card-body">
				<p>
					<?= $this->translate('Probably your application requires a database access. If you choose the complex user system, then Skyline CMS requires access to a database as well.<br>
					You can specify a primary database and a fallback database, if the primary does not work.') ?>
				</p>
				<span class="badge badge-danger badge-pill"><?= $this->translate('Not configured') ?></span>
			</div>
			<div class="card-footer d-flex justify-content-between">
				<button class="btn-sm btn btn-primary" onclick="location.href='<?=$this->buildURL('Admin', '/config-data-base')?>'"><?= $this->translate('Setup') ?></button>
			</div>
		</div>
	</div>

	<div class="col-md-6 mt-3">
		<div class="card">
			<h4 class="card-header"><?=$this->translate("Your Project")?></h4>
			<div class="card-body">
				<p>
					<?= $this->translate('If all works fine, you need to provide Skyline CMS some information about your website for correct delivery.') ?>
				</p>
				<span class="badge badge-danger badge-pill"><?= $this->translate('Not configured') ?></span>
			</div>
			<div class="card-footer d-flex justify-content-between">
				<button class="btn-sm btn btn-primary" onclick="location.href='<?=$this->buildURL('Admin', '/config-project')?>'"><?= $this->translate('Setup') ?></button>
			</div>
		</div>
	</div>
</div>