<?php
/**
 * BSD 3-Clause License
 *
 * Copyright (c) 2019, TASoft Applications
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

use Skyline\Render\Context\DefaultRenderContext;
use TASoft\Service\ServiceManager;

/**
 *
 * @var DefaultRenderContext $this
 * @var array $ENCODERS
 * @var int|string $PROBLEM
 * @var array $PROVIDERS
 * @var array $VALIDATORS
 */

$recommended = $this->translate('(recommended)');
$optional = $this->translate('(optional)');
$devOnly = $this->translate('(dev only!)');
?>
<style type="text/css">

</style>

<?=$BREAD?>

<h1><?=$this->translate("Security")?></h1>
<div class="alert alert-primary">
	<?= $this->translate('The security system is responsable to grant or deny access to your administration pages or also your website (if needed).<br>
					There are some settings you need to decide, how Skyline CMS should handle cases.') ?>
</div>

<hr>

<div class="card">
	<h4 class="card-header"><?= $this->translate('Password Encryption') ?></h4>
	<div class="card-body row">
		<div class="col-lg-8">
			<form action="" method="post">
				<input type="hidden" name="skyline-admin-csrf" value="<?=$CSRF?>">
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$ENCODERS['encoders'] & 1 ? 'checked':''?> name="encoder[]" value="1" aria-label="<?= $enableDisable = $this->translate('Enable or disable password encoder') ?>" title="<?=$enableDisable?>">
							</div>
							<div class="input-group-text">
								<input type="radio" <?=$ENCODERS['main'] == 1 ? 'checked':''?> name="main" value="1" class="is-invalid" aria-label="<?= $markEncoder = $this->translate('Mark this encoder as main encoder') ?>" title="<?=$markEncoder?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Message Digest') ?>" aria-describedby="md-help" aria-label="<?= $text = $this->translate('The message digest encryption') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $recommended ?></span>
						</div>
					</div>
					<small id="md-help" class="form-text text-muted"><?= $this->translate('The Message Digest encryption is a very common encryption method.') ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$ENCODERS['encoders'] & 2 ? 'checked':''?> name="encoder[]" value="2" aria-label="<?=$enableDisable?>" title="<?=$enableDisable?>">
							</div>
							<div class="input-group-text">
								<input type="radio" <?=$ENCODERS['main'] == 2 ? 'checked':''?> name="main" value="2" aria-label="<?=$markEncoder?>" title="<?=$markEncoder?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('BCrypt') ?>" aria-describedby="bc-help" aria-label="<?= $text = $this->translate('The bcryt encryption') ?>" title="<?=$text?>">
						<select class="custom-select" name="cost" aria-label="<?= $text = $this->translate('The bcryt encryption cost (4-31)') ?>" title="<?=$text?>">
							<?php
							for($e=4;$e<=31;$e++) {
								if($ENCODERS["cost"] == $e)
									echo "<option selected value='$e'>", $this->translate("Cost $e"), "</option>";
								else
									echo "<option value='$e'>", $this->translate("Cost $e"), "</option>";
							}
							?>
						</select>
						<div class="input-group-append">
							<span class="input-group-text"><?= $optional ?></span>
						</div>
					</div>
					<small id="bc-help" class="form-text text-muted"><?= $this->translate('The bcrypt is special designed for password encryption') ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$ENCODERS['encoders'] & 4 ? 'checked':''?> name="encoder[]" value="4" aria-label="<?=$enableDisable?>" title="<?=$enableDisable?>">
							</div>
							<div class="input-group-text">
								<input type="radio" <?=$ENCODERS['main'] == 4 ? 'checked':''?> name="main" value="4" aria-label="<?=$markEncoder?>" title="<?=$markEncoder?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('HTTP Digest A1') ?>" aria-describedby="a1-help" aria-label="<?= $text = $this->translate('The builtin http digest encryption') ?>" title="<?=$text?>">
						<input type="text" class="form-control" value="<?=htmlspecialchars($ENCODERS['realm'])?>" name="realm" placeholder="<?= $this->translate('Realm') ?>" aria-label="<?= $text = $this->translate('The realm of your Application.') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $optional ?></span>
						</div>
					</div>
					<small id="a1-help" class="form-text text-muted"><?= $this->translate('If you want to identify your client by the default http mechanism, then you should enable the A1 encryption and also mark it as main encoder.') ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$ENCODERS['encoders'] & 8 ? 'checked':''?> name="encoder[]" value="8" aria-label="<?=$enableDisable?>" title="<?=$enableDisable?>">
							</div>
							<div class="input-group-text">
								<input type="radio" <?=$ENCODERS['main'] == 8 ? 'checked':''?> name="main" value="8" aria-label="<?=$markEncoder?>" title="<?=$markEncoder?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Plaintext With Salt') ?>" aria-describedby="ps-help" aria-label="<?= $text = $this->translate('Plaintext With Salt') ?>" title="<?=$text?>">
						<input type="text" class="form-control" value="<?=htmlspecialchars($ENCODERS['salt'])?>" name="salt" placeholder="<?= $this->translate('Salt') ?>" aria-label="<?= $text = $this->translate('A salt string to make difference beteen applications') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $devOnly ?></span>
						</div>
					</div>
					<small id="ps-help" class="form-text text-muted"><?= $this->translate('This encoder appends the salt to the plain password to distinguish between diffent applications with same credentials.') ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$ENCODERS['encoders'] & 16 ? 'checked':''?> name="encoder[]" value="16" aria-label="<?=$enableDisable?>" title="<?=$enableDisable?>">
							</div>
							<div class="input-group-text">
								<input type="radio" <?=$ENCODERS['main'] == 16 ? 'checked':''?> name="main" value="16" aria-label="<?=$markEncoder?>" title="<?=$markEncoder?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Plaintext') ?>" aria-describedby="p-help" aria-label="<?= $text = $this->translate('Plaintext') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $devOnly ?></span>
						</div>
					</div>
					<small id="p-help" class="form-text text-muted"><?= $this->translate('This encoder does not encrypt any password.') ?></small>
				</div>

				<div class="form-group">
					<button class="btn btn-outline-primary" name="apply-encryption"><?= $this->translate('Save') ?></button>
				</div>
			</form>
		</div>
		<div class="col-lg-4">
			<p>
				<?= $this->translate('Here you specify the password encryption order.') ?>
			</p>
			<p class="alert alert-danger">
				<?=$this->translate('Skyline CMS never stores plain passwords in production!<br>
				If you don\'t disable those encoders, then a login might fail.')?>
			</p>
			<p>
				<?= $this->translate('The encryption order means, that a password may be stored in one of the enabled encryption.<br>
				On login, Skyline CMS tries to verify the password by the given encryption order.') ?>
			</p>
			<p>
				<?= $this->translate('If you create a new user or assuming you allow new membership, then Skyline CMS will encode a new password using the encoder marked as main encoder.') ?>
			</p>
			<p>
				<?= $this->translate('To reset an entered value, type ') ?><code>@default</code>.
			</p>
			<p class="alert alert-warning">
				<?= $this->translate('Please note that changing attributes of an encoder invalidates already stored credentials!') ?>
			</p>
		</div>
	</div>
</div>


<div class="card mt-5">
	<h4 class="card-header"><?= $this->translate('Identity') ?></h4>
	<div class="card-body row">
		<div class="col-lg-8">
			<form action="" method="post">
				<input type="hidden" name="skyline-admin-csrf" value="<?=$CSRF?>">
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$PROVIDERS['providers'] & 1 ? 'checked' : ''?> name="identity[]" value="1" aria-label="<?= $enableDisable = $this->translate('Enable or disable identity provider') ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('HTML Form') ?>" aria-describedby="frm-help" aria-label="<?= $text = $this->translate('Reads a HTML Form request to obtain username and password.') ?>" title="<?=$text?>">
						<input type="text" class="form-control" value="<?=htmlspecialchars($PROVIDERS['username_field'])?>" name="username_field" placeholder="<?= $this->translate('Username Field') ?>" aria-label="<?= $text = $this->translate('The HTML form input name to look for a transmitted username.') ?>" title="<?=$text?>">
						<input type="text" class="form-control" value="<?=htmlspecialchars($PROVIDERS['password_field'])?>" name="password_field" placeholder="<?= $this->translate('Password Field') ?>" aria-label="<?= $text = $this->translate('The HTML form input name to look for a transmitted password.') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $recommended ?></span>
						</div>
					</div>
					<small id="frm-help" class="form-text text-muted"><?= $text ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$PROVIDERS['providers'] & 2 ? 'checked' : ''?> name="identity[]" value="2" aria-label="<?= $enableDisable  ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Session') ?>" aria-describedby="sess-help" aria-label="<?= $text = $this->translate('If the login was successful, the credentials are stored in the session. The session finishes when the client close his browser.') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $recommended ?></span>
						</div>
					</div>
					<small id="sess-help" class="form-text text-muted"><?= $text ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$PROVIDERS['providers'] & 4 ? 'checked' : ''?> name="identity[]" value="4" aria-label="<?= $enableDisable  ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Remember Me') ?>" aria-describedby="rem-help" aria-label="<?= $desc = $this->translate('Again, if the login was successful, the credentials are stored in a remember me token. This is longer valid. See the security settings later in your application.') ?>" title="<?=$desc?>">
						<input type="text" class="form-control" value="<?=htmlspecialchars($PROVIDERS['remember_me_field'])?>" name="remember_me_field" placeholder="<?= $this->translate('Remember Me Field') ?>" aria-label="<?= $text = $this->translate('The HTML form input name to look for transmitted remember me service.') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $optional ?></span>
						</div>
					</div>
					<small id="rem-help" class="form-text text-muted"><?= $desc ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$PROVIDERS['providers'] & 8 ? 'checked' : ''?> name="identity[]" value="8" aria-label="<?= $enableDisable  ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('HTTP Digest') ?>" aria-describedby="dig-help" aria-label="<?= $desc = $this->translate('Challenge the client by the builtin http authentication method digest. If you choose this, you should also choose the http digest A1 password encoder.') ?>" title="<?=$desc?>">
						<input type="text" class="form-control" value="<?=htmlspecialchars($ENCODERS['realm'])?>" name="realm-digest" placeholder="<?= $this->translate('Realm') ?>" aria-label="<?= $text = $this->translate('The realm of your Application.') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $optional ?></span>
						</div>
					</div>
					<small id="dig-help" class="form-text text-muted"><?= $desc ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$PROVIDERS['providers'] & 16 ? 'checked' : ''?> name="identity[]" value="16" aria-label="<?= $enableDisable  ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('HTTP Basic') ?>" aria-describedby="bas-help" aria-label="<?= $desc = $this->translate('Challenge the client by the builtin http authentication method basic. This requires the plaintext password encoder and is only allowed in develompent') ?>" title="<?=$desc?>">
						<input type="text" class="form-control" value="<?=htmlspecialchars($PROVIDERS['realm'])?>" name="realm-basic" placeholder="<?= $this->translate('Realm') ?>" aria-label="<?= $text = $this->translate('The realm of your Application.') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $devOnly ?></span>
						</div>
					</div>
					<small id="bas-help" class="form-text text-muted"><?= $desc ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$PROVIDERS['providers'] & 32 ? 'checked' : ''?> name="identity[]" value="32" aria-label="<?= $enableDisable  ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Anonymous') ?>" aria-describedby="ano-help" aria-label="<?= $desc = $this->translate('Creates an anonymous identity for each client without username and password. But a client has always the same identity.') ?>" title="<?=$desc?>">
						<input type="text" class="form-control" value="<?=htmlspecialchars($PROVIDERS['anonymous'])?>" name="anonymous-user" placeholder="<?= $this->translate('Anonymous Username') ?>" aria-label="<?= $text = $this->translate('The realm of your Application.') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $optional ?></span>
						</div>
					</div>
					<small id="ano-help" class="form-text text-muted"><?= $desc ?></small>
				</div>

				<div class="form-group">
					<button name="apply-identity" class="btn btn-outline-primary"><?= $this->translate('Save') ?></button>
				</div>
			</form>
		</div>
		<div class="col-lg-4">
			<p>
				<?= $this->translate('Identity providers tell Skyline CMS how to obtain and challenge a client for its identity.') ?>
			</p>
			<p>
				<?= $this->translate('Password encoders and identity providers must match. Here are some examples:') ?>
			</p>
			<?=$this->translate('<p>
				<code>Message Digest</code>, <code>BCrypt</code> and/or <code>Plaintext</code> work with <br>
				<code>HTML Form</code>, <code>Session</code> and <code>Remember Me</code>.
			</p>
			<p>
				<code>HTTP Digest</code> only works with <code>HTTP Digest A1</code>.<br>
				<em class="text-muted" style="font-size: 80%%">(Please keep in mind that encoded passwords are realm and user dependent!)</em>
			</p>
			<p>
				<code>HTTP Basic</code> works with all except <code>HTTP Digest A1</code>
			</p>
			<p>
				The <code>Anonymous</code> identity always work without password encoders.<br>
				If you don\'t specify a username, Skyline CMS will fail authenticate an anonymous identity.<br>
				<span class="text-danger">Please only assign users with low access rights to the anonymous identity!</span>
			</p>
			<p>
				The <code>HTML Form</code> should be combined with <code>Session</code> and/or <code>Remember Me</code>. if not, the user needs to enter its username and password for each request again.
			</p>')?>
		</div>
	</div>
</div>



<div class="card mt-5">
	<h4 class="card-header"><?= $this->translate('Login Validators') ?></h4>
	<div class="card-body row">
		<div class="col-lg-8">
			<form action="" method="post">
				<input type="hidden" name="skyline-admin-csrf" value="<?=$CSRF?>">
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$VALIDATORS['validators'] & 1 ? 'checked' : ''?> name="validator[]" value="1" aria-label="<?= $enableDisable = $this->translate('Enable or disable Validator') ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Client Brute Force') ?>" aria-describedby="cbf-help" aria-label="<?= $desc = $this->translate('Blocks too many failed login attempts by ip address of a client.') ?>" title="<?=$desc?>">
						<input type="text" class="form-control" size="3" value="<?=htmlspecialchars($VALIDATORS['cb_attempts'])?>" name="cb_attempts" placeholder="<?= $this->translate('Max') ?>" aria-label="<?= $text = $this->translate('Maximal failed attempts') ?>" title="<?=$text?>">
						<input type="text" class="form-control" size="6" value="<?=htmlspecialchars($VALIDATORS['cb_block_time'])?>" name="cb_block_time" placeholder="<?= $this->translate('Wait') ?>" aria-label="<?= $text = $this->translate('Set time interval in seconds to block until next attempt.') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $recommended ?></span>
						</div>
					</div>
					<small id="cbf-help" class="form-text text-muted"><?= $desc ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$VALIDATORS['validators'] & 2 ? 'checked' : ''?> name="validator[]" value="2" aria-label="<?= $enableDisable ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Server Brute Force') ?>" aria-describedby="sbf-help" aria-label="<?= $desc = $this->translate('Blocks too many failed login attempts by a URI on the server') ?>" title="<?=$desc?>">
						<input type="text" class="form-control" size="3" value="<?=htmlspecialchars($VALIDATORS['sb_attempts'])?>" name="sb_attempts" placeholder="<?= $this->translate('Max') ?>" aria-label="<?= $text = $this->translate('Maximal failed attempts') ?>" title="<?=$text?>">
						<input type="text" class="form-control" size="6" value="<?=htmlspecialchars($VALIDATORS['sb_block_time'])?>" name="sb_block_time" placeholder="<?= $this->translate('Wait') ?>" aria-label="<?= $text = $this->translate('Set time interval in seconds to block until next attempt.') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $optional ?></span>
						</div>
					</div>
					<small id="sbf-help" class="form-text text-muted"><?= $desc ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$VALIDATORS['validators'] & 4 ? 'checked' : ''?> name="validator[]" value="4" aria-label="<?= $enableDisable ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Auto Logout') ?>" aria-describedby="alo-help" aria-label="<?= $desc = $this->translate('Cancels logged user session if there was no activity for too long time.') ?>" title="<?=$desc?>">
						<input type="text" class="form-control" value="<?=htmlspecialchars($VALIDATORS['autologout'])?>" name="autologout" placeholder="<?= $this->translate('Time Interval') ?>" aria-label="<?= $text = $this->translate('Set the maximal time interval in seconds without a user action.') ?>" title="<?=$text?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $optional ?></span>
						</div>
					</div>
					<small id="alo-help" class="form-text text-muted"><?= $desc ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$VALIDATORS['validators'] & 8 ? 'checked' : ''?> name="validator[]" value="8" aria-label="<?= $enableDisable ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Permission Changed') ?>" aria-describedby="pc-help" aria-label="<?= $desc = $this->translate('Cancels logged user session if the permissions of the user changed during the session.') ?>" title="<?=$desc?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $optional ?></span>
						</div>
					</div>
					<small id="pc-help" class="form-text text-muted"><?= $desc ?></small>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-prepend">
							<div class="input-group-text">
								<input type="checkbox" <?=$VALIDATORS['validators'] & 16 ? 'checked' : ''?> name="validator[]" value="16" aria-label="<?= $enableDisable ?>" title="<?=$enableDisable?>">
							</div>
						</div>
						<input type="text" class="form-control" readonly value="<?= $this->translate('Update Last Login Date') ?>" aria-describedby="ulld-help" aria-label="<?= $desc = $this->translate('Just for information it stores the date and time of all successful logins.') ?>" title="<?=$desc?>">
						<div class="input-group-append">
							<span class="input-group-text"><?= $optional ?></span>
						</div>
					</div>
					<small id="ulld-help" class="form-text text-muted"><?= $desc ?></small>
				</div>

				<div class="form-group">
					<button name="apply-validators" class="btn btn-outline-primary"><?= $this->translate('Save') ?></button>
				</div>
			</form>
		</div>
		<div class="col-lg-4">
			<p>
				<?= $this->translate('The validators are active while login process of a client.') ?>
			</p>
		</div>
	</div>
</div>


<?php

if(is_string($PROBLEM )) {
	?>
	<div class="modal banner fade" id="modal-failed" tabindex="-1" role="dialog" aria-labelledby="modal-success-title" aria-hidden="true">
		<div class="modal-dialog success" role="document">
			<div class="modal-content">
				<div class="modal-header bg-danger text-white">
					<h4 class="modal-title text-center"><?= $this->translate('Settings Not Updated') ?></h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true" class="white-text">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<i class="fa fa-times fa-4x text-danger animated rotateIn mb-3"></i>
						<p>
							<?=$PROBLEM?>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="application/javascript">
        $(function() {
            $("#modal-failed").modal("show");
        });
	</script>
	<?php
} elseif($_SESSION["updated"] ?? false) {
	unset($_SESSION["updated"]);
	?>
	<div class="modal banner fade" id="modal-success" tabindex="-1" role="dialog" aria-labelledby="modal-success-title" aria-hidden="true">
		<div class="modal-dialog success" role="document">
			<div class="modal-content">
				<div class="modal-header bg-success text-white">
					<h4 class="modal-title text-center" id="modal-success-title"><?= $this->translate('Settings Updated') ?></h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true" class="white-text">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<i class="fa fa-check fa-4x text-success animated rotateIn mb-3"></i>
						<p>
							<?= $this->translate('The changed settings were updated successfully.') ?>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="application/javascript">
		$(function() {
			$("#modal-success").modal("show");
		});
	</script>
	<?php
}
