<?php
/**
 * BSD 3-Clause License
 *
 * Copyright (c) 2019, TASoft Applications
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

use Skyline\HTML\Bootstrap\Breadcrumb;
use Skyline\Render\Context\DefaultRenderContext;

/**
 * @require FontAwesome
 * @require Animation
 * @var DefaultRenderContext $this
 * @var int $security
 */
?>
<style type="text/css">

</style>

<h1><?=$this->translate("Forgot Password")?></h1>
<p class="alert alert-primary">
	<?=$this->translate('You forgot your password?<br>
	That\'s no problem.<br>
	So Skyline CMS hashes passwords before storing them. Hashing means a one way direction encryption of your original password.<br>
	We can not tell you what password you\'ve set, but we can send you an email including a reset link.')?>
</p>

<hr class="my-5">

<div class="row">
	<div class="col-lg-8">
		<form action="" method="post">
			<input type="hidden" name="skyline-admin-csrf" value="<?=$CSRF?>">

			<div class="form-group row">
				<label for="username" class="col-md-2 col-form-label"><?= $this->translate('Username') ?></label>
				<div class="col-md-10">
					<div class="input-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fa fa-at"></i></span>
						</div>
						<input type="text" class="form-control" id="username" name="username" value="<?=htmlspecialchars($_POST["username"] ?? "")?>">
					</div>
				</div>
			</div>

			<div class="form-group offset-lg-2">
				<button name="reset-password" class="mt-3 btn btn-outline-primary"><?= $this->translate('Reset Password') ?></button>
			</div>
		</form>
	</div>
	<div class="col-lg-4">
		<p>
			<?=$this->translate('Please enter your username or the email you\'ve used as membership contact.')?>
		</p>
	</div>
</div>

<?php

if($SUCCESS === -1) {
	?>
	<div class="modal banner fade" id="modal-failed" tabindex="-1" role="dialog" aria-labelledby="modal-success-title" aria-hidden="true">
		<div class="modal-dialog success" role="document">
			<div class="modal-content">
				<div class="modal-header bg-danger text-white">
					<h4 class="modal-title text-center"><?= $this->translate('Failed') ?></h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true" class="white-text">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<i class="fa fa-times fa-4x text-danger animated rotateIn mb-3"></i>
						<p>
							<?= $this->translate('Could not send password reset link.') ?>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="application/javascript">
        $(function() {
            $("#modal-failed").modal("show");
        });
	</script>
	<?php
} elseif($SUCCESS === 1) {
	?>
	<div class="modal banner fade" id="modal-success" tabindex="-1" role="dialog" aria-labelledby="modal-success-title" aria-hidden="true">
		<div class="modal-dialog success" role="document">
			<div class="modal-content">
				<div class="modal-header bg-success text-white">
					<h4 class="modal-title text-center" id="modal-success-title"><?= $this->translate('Sent') ?></h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true" class="white-text">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<i class="fa fa-check fa-4x text-success animated rotateIn mb-3"></i>
						<p>
							<?= $this->translate('Skyline CMS sent an email with a password reset link to the account\'s email address.') ?>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="application/javascript">
        $(function() {
            $("#modal-success").modal("show");
        });
	</script>
	<?php
} else {
	?>
	<script type="application/javascript">
        $(function() {
            $("#username").focus();
        })
	</script>
	<?php
}