<?php
/**
 * BSD 3-Clause License
 *
 * Copyright (c) 2019, TASoft Applications
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

use Skyline\CMS\Security\Tool\PasswordResetTool;
use Skyline\HTML\Bootstrap\Breadcrumb;
use Skyline\Render\Context\DefaultRenderContext;
use TASoft\Service\ServiceManager;

/**
 * @require FontAwesome
 * @require Animation
 * @var DefaultRenderContext $this
 * @var array $VALIDATION
 */
$sm = ServiceManager::generalServiceManager();
$errorField = "";
?>
<style type="text/css">

</style>

<h1><?=$this->translate("Register New Membership")?></h1>

<div class="alert alert-primary">
	<?= $this->translate('Welcome to the Skyline CMS Admin panel crew. We invite you to enter your contact data and then you will get access to our administration.') ?>
</div>

<hr>

<?php
if($verify_email) {
	?>
	<div class="alert alert-warning">
		<h5 class="alert-heading"><?= $this->translate('Email Verification Required') ?></h5>
		<p>
			<?=$this->translate('To join our application, Skyline CMS will verify your email address.<br>
			After all data is entered and validated, Skyline CMS will send an email to the entered address.<br>
			This email contains an activation link. You are kindly asked to click on that link or copy it into your browser\'s address bar.<br>
			finally then your account gets created.')?>
		</p>
	</div>
	<?php
}
?>

<div class="card">
	<div class="card-body row">
		<div class="col-lg-8">
			<form action="" method="post">
				<input type="hidden" name="skyline-admin-csrf" value="<?=$CSRF?>">

				<div class="form-group row">
					<label for="username" class="col-md-4 col-form-label"><?=$this->translate('Username')?>*</label>
					<div class="col-md-8">
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fa fa-user"></i></span>
							</div>
							<input type="text" class="form-control<?=$VALIDATION["username"]["class"]?>" id="username" name="username" value="<?=htmlspecialchars($_POST["username"] ?? "")?>">
							<div class="invalid-feedback">
								<?php
								if($fb = $VALIDATION["username"]["feedback"] ?? '') {
									echo $fb;
									if(!$errorField)
										$errorField = 'username';
								}
								?>
							</div>
						</div>
					</div>
				</div>

				<div class="form-group row">
					<label for="email" class="col-md-4 col-form-label"><?= $this->translate('Email') ?>*</label>
					<div class="col-md-8">
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fa fa-at"></i></span>
							</div>
							<input type="text" class="form-control<?=$VALIDATION["email"]["class"]?>" id="email" name="email" value="<?=htmlspecialchars($_POST["email"] ?? "")?>">
							<div class="invalid-feedback">
								<?php
								if($fb = $VALIDATION["email"]["feedback"] ?? '') {
									echo $fb;
									if(!$errorField)
										$errorField = 'email';
								}
								?>
							</div>
						</div>
					</div>
				</div>

				<div class="form-group row">
					<label for="prename" class="col-md-4 col-form-label"><?= $this->translate('Name') ?></label>
					<div class="col-md-8">
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fa fa-tag"></i></span>
							</div>
							<input type="text" class="form-control<?=$VALIDATION["prename"]["class"]?>" id="prename" name="prename" value="<?=htmlspecialchars($_POST["prename"] ?? "")?>">
						</div>
					</div>
				</div>

				<div class="form-group row">
					<label for="surname" class="col-md-4 col-form-label"><?= $this->translate('Surname') ?></label>
					<div class="col-md-8">
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fa fa-tag"></i></span>
							</div>
							<input type="text" class="form-control<?=$VALIDATION["surname"]["class"]?>" id="surname" name="surname" value="<?=htmlspecialchars($_POST["surname"] ?? "")?>">
						</div>
					</div>
				</div>

				<?php
				if(!$verify_email) {
					?>
					<div class="form-group row">
						<label for="password" class="col-md-4 col-form-label"><?= $this->translate('Password') ?></label>

						<div class="col-md-8">
							<div class="input-group">
								<div class="input-group-prepend">
									<span class="input-group-text"><i class="fa fa-key"></i></span>
								</div>
								<input type="password" class="form-control<?=$PROBLEM > 0 ? ' is-invalid' : ($PROBLEM == -1? ' is-valid' : '')?>" id="password" name="password" value="<?=htmlspecialchars($_POST["password"] ?? '')?>">
								<div class="invalid-feedback">
									<?php
									if($PROBLEM && !$errorField)
										$errorField = 'password';

									switch ($PROBLEM) {
										case 1: echo $this->translateGlobal("Password must not be empty"); break;
										case 2: echo $this->translateGlobal("Passwort must contain at least %d characters.", NULL, $sm->getParameter("security.password.reset.min-length")); break;
										case 4: echo $this->translateGlobal("Passwort must contain at least one number 0-9."); break;
										case 8: echo $this->translateGlobal("Passwort must contain at least one uppercase character A-Z."); break;
										case 16: echo $this->translateGlobal("Passwort must contain at least one lowercase character a-z."); break;
										case 32: echo $this->translateGlobal("Passwort must contain at least one special character: +-*/?!$;:_%%&@(){}[]#="); break;
										case 64: echo $this->translateGlobal("Password must only contain characters: %s", NULL, $sm->getParameter("security.password.reset.must-contain")); break;
										case 128: echo $this->translateGlobal("Password must not contain characters: %s", NULL, $sm->getParameter("security.password.reset.must-not-contain")); break;
									}
									?>
								</div>
							</div>
						</div>
					</div>

					<div class="form-group row">
						<label for="passwordv" class="col-md-4 col-form-label"><?= $this->translate('Verify') ?></label>

						<div class="col-md-8">
							<div class="input-group">
								<div class="input-group-prepend">
									<span class="input-group-text"><i class="fa fa-key"></i></span>
								</div>
								<input type="password" class="form-control<?=$PROBLEM == -1?' is-invalid' : ''?>" id="passwordv" name="passwordv" value="<?=htmlspecialchars($_POST["passwordv"] ?? '')?>">
								<div class="invalid-feedback">
									<?= $this->translate('Password verification does not match the password.') ?>
								</div>
							</div>
						</div>
					</div>
					<?php
				}
				?>

				<div class="form-group row">
					<div class="col-md-4">&nbsp;</div>
					<div class="col-md-8">
						<button name="apply-membership" class="btn btn-outline-primary"><?= $this->translate('Register') ?></button>
					</div>
				</div>
			</form>
		</div>
		<div class="col-lg-4">
			<p>
				<?= $this->translate('Please fill in all fields marked with a (*).') ?>
			</p>
			<p class="alert alert-primary">
				<?= $this->translate('Skyline CMS will create a cookie to validate your membership.') ?>
			</p>
		</div>
	</div>
</div>

<?php

if($SUCCESS === -1) {
	?>
	<div class="modal banner fade" id="modal-failed" tabindex="-1" role="dialog" aria-labelledby="modal-success-title" aria-hidden="true">
		<div class="modal-dialog success" role="document">
			<div class="modal-content">
				<div class="modal-header bg-danger text-white">
					<h4 class="modal-title text-center"><?= $this->translate('Failed') ?></h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true" class="white-text">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<i class="fa fa-times fa-4x text-danger animated rotateIn mb-3"></i>
						<p>
							<?= $this->translate('Could not create membership request. Please try again later.') ?>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="application/javascript">
        $(function() {
            $("#modal-failed").modal("show");
        });
	</script>
	<?php
} elseif($SUCCESS === 1) {
	?>
	<div class="modal banner fade" id="modal-success" tabindex="-1" role="dialog" aria-labelledby="modal-success-title" aria-hidden="true">
		<div class="modal-dialog success" role="document">
			<div class="modal-content">
				<div class="modal-header bg-success text-white">
					<h4 class="modal-title text-center" id="modal-success-title"><?= $this->translate('Sent') ?></h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true" class="white-text">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<i class="fa fa-check fa-4x text-success animated rotateIn mb-3"></i>
						<p>
							<?= $this->translate('Skyline CMS sent an email with an activation link to the passed email address. Click it or copy it fully to your browser\'s address bar to activate your membership.') ?>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="application/javascript">
        $(function() {
            $("#modal-success").modal("show");
        });
	</script>
	<?php
}
?>

<script type="application/javascript">
	<?php
	if($errorField)
		echo "$('#$errorField').focus();";
	?>
</script>