<?php
/**
 * BSD 3-Clause License
 *
 * Copyright (c) 2019, TASoft Applications
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

use Skyline\CMS\Security\Tool\PasswordResetTool;
use Skyline\HTML\Bootstrap\Breadcrumb;
use Skyline\Render\Context\DefaultRenderContext;
use TASoft\Service\ServiceManager;

/**
 * @require FontAwesome
 * @require Animation
 * @var DefaultRenderContext $this
 * @var int $security
 */
$sm = ServiceManager::generalServiceManager();
?>
<style type="text/css">

</style>

<h1><?=$this->translate("Define New Password")?></h1>



<?if($ERROR==-1):?>
	<div class="alert-danger alert" role="alert">
		<h2 class="alert-heading"><?= $this->translate('System Error') ?></h2>
		<p>
			<?= $this->translate('The password reset service is disabled by this application.') ?>
		</p>
	</div>
<?elseif ($ERROR==PasswordResetTool::ERROR_CODE_TIME_LIMIT_REACHED):?>
	<div class="alert alert-danger" role="alert">
		<h2 class="alert-heading"><?= $this->translate('Timed out') ?></h2>
		<p>
			<?= $this->translate('For security reason the password reset links remains valid for a limited timeout.') ?>
		</p>
		<p>
			<a href="/admin/forgot-password/request-reset-link"><?= $this->translate('Request a new reset link?') ?></a>
		</p>
	</div>
<?elseif ($ERROR==PasswordResetTool::ERROR_CODE_NOT_DEACTIVATED):?>
	<div class="alert alert-danger" role="alert">
		<h2 class="alert-heading"><?= $this->translate('Denied Request') ?></h2>
		<p>
			<?= $this->translate('Your reset request link contains information about a user that is no longer active or available.') ?>
		</p>
	</div>
<?elseif($ERROR==PasswordResetTool::ERROR_CODE_INVALID_TOKEN || !$OK):?>
	<div class="alert alert-danger" role="alert">
		<h2 class="alert-heading"><?= $this->translate('Invalid Request') ?></h2>
		<p>
			<?= $this->translate('The reset request link was not transmitted completly. Please make sure to copy the whole link.') ?>
		</p>
	</div>
<?else:?>
	<form action="" method="post">
		<input type="hidden" name="skyline-admin-csrf" value="<?=$CSRF?>">

		<p class="alert alert-primary">
			<?= $this->translate('Here you can define a new password for your account.<br>
			There might exist some password conditions which are described below.') ?>
		</p>

		<?php
		if($pw_conds == 0) {
			?>
			<p class="alert alert-info">
				<?= $this->translate('There are no restrictions. You can choose any password you want.') ?>
			</p>
			<?php
		} else {
			echo "<dl class='alert alert-info'>";
			if($pw_conds & 1) {
				echo "<dt>", $this->translateGlobal("Not Empty"), "</dt>";
				echo "<dd>", $this->translateGlobal("Passwort must not be empty"), "</dd>";
			}
			if($pw_conds & 2) {
				echo "<dt>", $this->translateGlobal("Minimum Length"), "</dt>";
				echo "<dd>", $this->translateGlobal("Passwort must contain at least %d characters.", NULL, $sm->getParameter("security.password.reset.min-length")), "</dd>";
			}
			if($pw_conds & 4) {
				echo "<dt>", $this->translateGlobal("Numbers"), "</dt>";
				echo "<dd>", $this->translateGlobal("Passwort must contain at least one number 0-9."), "</dd>";
			}
			if($pw_conds & 8) {
				echo "<dt>", $this->translateGlobal("Upper Case Characters"), "</dt>";
				echo "<dd>", $this->translateGlobal("Passwort must contain at least one uppercase character A-Z."), "</dd>";
			}
			if($pw_conds & 16) {
				echo "<dt>", $this->translateGlobal("Lower Case Characters"), "</dt>";
				echo "<dd>", $this->translateGlobal("Passwort must contain at least one lowercase character a-z."), "</dd>";
			}
			if($pw_conds & 32) {
				echo "<dt>", $this->translateGlobal("Soecial Characters"), "</dt>";
				echo "<dd>", $this->translateGlobal("Passwort must contain at least one special character: +-*/?!$;:_%%&@(){}[]#="), "</dd>";
			}
			if($pw_conds & 64) {
				echo "<dt>", $this->translateGlobal("Must Contain Characters"), "</dt>";
				echo "<dd>", $this->translateGlobal("Password must only contain characters: %s", NULL, $sm->getParameter("security.password.reset.must-contain")), "</dd>";
			}
			if($pw_conds & 128) {
				echo "<dt>", $this->translateGlobal("Must Not Contain Characters"), "</dt>";
				echo "<dd>", $this->translateGlobal("Password must not contain characters: %s", NULL, $sm->getParameter("security.password.reset.must-not-contain")), "</dd>";
			}
			echo "</dl>";
		}
		?>

		<div class="form-group row">
			<label for="password" class="col-md-2 col-form-label"><?= $this->translate('Password') ?></label>

			<div class="col-md-10">
				<div class="input-group">
					<div class="input-group-prepend">
						<span class="input-group-text"><i class="fa fa-key"></i></span>
					</div>
					<input type="password" class="form-control<?=$PROBLEM > 0 ? ' is-invalid' : ($PROBLEM == -1? ' is-valid' : '')?>" id="password" name="password" value="<?=htmlspecialchars($_POST["password"] ?? '')?>">
					<div class="invalid-feedback">
					<?php
					switch ($PROBLEM) {
						case 1: echo $this->translateGlobal("Password must not be empty"); break;
						case 2: echo $this->translateGlobal("Passwort must contain at least %d characters.", NULL, $sm->getParameter("security.password.reset.min-length")); break;
						case 4: echo $this->translateGlobal("Passwort must contain at least one number 0-9."); break;
						case 8: echo $this->translateGlobal("Passwort must contain at least one uppercase character A-Z."); break;
						case 16: echo $this->translateGlobal("Passwort must contain at least one lowercase character a-z."); break;
						case 32: echo $this->translateGlobal("Passwort must contain at least one special character: +-*/?!$;:_%%&@(){}[]#="); break;
						case 64: echo $this->translateGlobal("Password must only contain characters: %s", NULL, $sm->getParameter("security.password.reset.must-contain")); break;
						case 128: echo $this->translateGlobal("Password must not contain characters: %s", NULL, $sm->getParameter("security.password.reset.must-not-contain")); break;
					}
					?>
					</div>
				</div>
			</div>
		</div>

		<div class="form-group row">
			<label for="passwordv" class="col-md-2 col-form-label"><?= $this->translate('Verify') ?></label>

			<div class="col-md-10">
				<div class="input-group">
					<div class="input-group-prepend">
						<span class="input-group-text"><i class="fa fa-key"></i></span>
					</div>
					<input type="password" class="form-control<?=$PROBLEM == -1?' is-invalid' : ''?>" id="passwordv" name="passwordv" value="">
					<div class="invalid-feedback">
						<?= $this->translate('Password verification does not match the password.') ?>
					</div>
				</div>
			</div>
		</div>

		<div class="form-group row">
			<div class="col-lg-2">&nbsp;</div>
			<div class="col-lg-10">
				<div class="form-group">
					<button name="reset-passwd" class="btn btn-outline-primary"><?= $this->translate('Save') ?></button>
				</div>
			</div>
		</div>
	</form>

	<script type="application/javascript">
		<?php
		if($PROBLEM == -1)
			echo "$('#passwordv').focus();";
		else
			echo "$('#password').focus();";
		?>
	</script>
<?endif;