<?php
/**
 * BSD 3-Clause License
 *
 * Copyright (c) 2019, TASoft Applications
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

use Skyline\Render\Context\DefaultRenderContext;

/**
 *
 * @var DefaultRenderContext $this
 */
?>
<?=$BREAD?>

<h1><?= $this->translate('Profile') ?></h1>
<div class="alert alert-primary">
	<?= $this->translate('Adjust here your profile') ?>
</div>

<hr>

<div class="row">
	<div class="col-md-6 col-lg-4 mb-4">
		<div class="card">
			<div class="card-header text-center">
				<?= $this->translate('Name') ?>
			</div>
			<div class="card-body">
				<form action="" method="post">
					<input type="hidden" name="skyline-admin-csrf" value="<?=$CSRF?>">

					<div class="form-group">
						<label for="prename"><?= $text = $this->translate('Name') ?></label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fa fa-tag"></i></span>
							</div>
							<input type="text" name="my-prename" class="form-control" id="prename" aria-describedby="prenameHelp" placeholder="<?=$text?>" value="<?=htmlspecialchars($PROFILE["prename"]??'')?>">
						</div>
						<small id="prenameHelp" class="form-text text-muted"><?= $this->translate('Optionally your name (displayed in the menu and used to send emails.)') ?></small>
					</div>

					<div class="form-group">
						<label for="surname"><?= $text = $this->translate('Surname') ?></label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fa fa-tag"></i></span>
							</div>
							<input type="text" name="my-surname" class="form-control" id="surname" aria-describedby="surnameHelp" placeholder="<?=$text?>" value="<?=htmlspecialchars($PROFILE["surname"]??'')?>">
						</div>
						<small id="surnameHelp" class="form-text text-muted"><?= $this->translate('Optionally your surname (displayed in the menu and used to send emails.)') ?></small>
					</div>

					<div class="form-group">
						<label for="email"><?= $text = $this->translate('Email') ?></label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fa fa-envelope"></i></span>
							</div>
							<input type="email" name="my-email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="<?=$text?>" value="<?=htmlspecialchars($PROFILE["email"]??'')?>">
						</div>
						<small id="emailHelp" class="form-text text-muted"><?= $this->translate('Required email address to contact you.') ?></small>
					</div>

					<div class="d-flex justify-content-center align-content-center">
						<?php
						if($PROFILE["id"] == -1) {
							?>
							<p class="alert alert-warning">
								<?=$this->translate('Your user is not part of the Skyline CMS\'s multiple user-system. So this properties can not be defined. ')?>
							</p>
							<?php
						} else {
							?>
							<button title="<?= $saveData = $this->translate('Save data') ?>" name="apply-name" class="action btn btn-outline-primary"><i class="fa fa-save fa-2x"></i></button>
							<?php
						}
						?>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<?php
if(is_string($PROBLEM )) {
	?>
	<div class="modal banner fade" id="modal-failed" tabindex="-1" role="dialog" aria-labelledby="modal-success-title" aria-hidden="true">
		<div class="modal-dialog success" role="document">
			<div class="modal-content">
				<div class="modal-header bg-danger text-white">
					<h4 class="modal-title text-center"><?= $this->translate('Settings Not Updated') ?></h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true" class="white-text">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<i class="fa fa-times fa-4x text-danger animated rotateIn mb-3"></i>
						<p>
							<?=$PROBLEM?>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="application/javascript">
        $(function() {
            $("#modal-failed").modal("show");
        });
	</script>
	<?php
} elseif($_SESSION["updated"] ?? false) {
	unset($_SESSION["updated"]);
	?>
	<div class="modal banner fade" id="modal-success" tabindex="-1" role="dialog" aria-labelledby="modal-success-title" aria-hidden="true">
		<div class="modal-dialog success" role="document">
			<div class="modal-content">
				<div class="modal-header bg-success text-white">
					<h4 class="modal-title text-center" id="modal-success-title"><?= $this->translate('Settings Updated') ?></h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true" class="white-text">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<i class="fa fa-check fa-4x text-success animated rotateIn mb-3"></i>
						<p>
							<?= $this->translate('The changed settings were updated successfully.') ?>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="application/javascript">
        $(function() {
            $("#modal-success").modal("show");
        });
	</script>
	<?php
}